CREATE DATABASE IF NOT EXISTS REAL_TIME_PIPELINE;

USE DATABASE REAL_TIME_PIPELINE;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE WAREHOUSE IF NOT EXISTS PIPELINE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PIPELINE_WH;

CREATE TABLE IF NOT EXISTS REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW (
    ID NUMBER AUTOINCREMENT,
    RAW_DATA VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);