CREATE TABLE IF NOT EXISTS REAL_TIME_PIPELINE.SILVER.WEATHER_CLEAN (
    ID NUMBER,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    WIND_SPEED FLOAT,
    WEATHER_TIMESTAMP TIMESTAMP_NTZ,
    INGESTED_AT TIMESTAMP_NTZ
);

INSERT INTO REAL_TIME_PIPELINE.SILVER.WEATHER_CLEAN
(
    ID,
    LATITUDE,
    LONGITUDE,
    TEMPERATURE,
    HUMIDITY,
    WIND_SPEED,
    WEATHER_TIMESTAMP,
    INGESTED_AT
)
SELECT
    ID,
    RAW_DATA:latitude::FLOAT,
    RAW_DATA:longitude::FLOAT,
    RAW_DATA:temperature::FLOAT,
    RAW_DATA:humidity::FLOAT,
    RAW_DATA:wind_speed::FLOAT,
    RAW_DATA:timesta    p::TIMESTAMP_NTZ,
    INGESTED_AT
FROM REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW;

CREATE OR REPLACE STREAM REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW_STREAM
ON TABLE REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW
APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK REAL_TIME_PIPELINE.SILVER.PROCESS_WEATHER_TASK
    WAREHOUSE = PIPELINE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW_STREAM'
    )
AS
INSERT INTO REAL_TIME_PIPELINE.SILVER.WEATHER_CLEAN
(
    ID,
    LATITUDE,
    LONGITUDE,
    TEMPERATURE,
    HUMIDITY,
    WIND_SPEED,
    WEATHER_TIMESTAMP,
    INGESTED_AT
)
SELECT
    ID,
    RAW_DATA:latitude::FLOAT,
    RAW_DATA:longitude::FLOAT,
    RAW_DATA:temperature::FLOAT,
    RAW_DATA:humidity::FLOAT,
    RAW_DATA:wind_speed::FLOAT,
    RAW_DATA:timestamp::TIMESTAMP_NTZ,
    INGESTED_AT
FROM REAL_TIME_PIPELINE.BRONZE.WEATHER_RAW_STREAM
WHERE METADATA$ACTION = 'INSERT';