CREATE OR REPLACE VIEW REAL_TIME_PIPELINE.GOLD.HOURLY_WEATHER AS

SELECT
    DATE_TRUNC('HOUR', WEATHER_TIMESTAMP) AS WEATHER_HOUR,

    ROUND(AVG(TEMPERATURE), 2) AS AVG_TEMPERATURE,
    ROUND(MIN(TEMPERATURE), 2) AS MIN_TEMPERATURE,
    ROUND(MAX(TEMPERATURE), 2) AS MAX_TEMPERATURE,

    ROUND(AVG(HUMIDITY), 2) AS AVG_HUMIDITY,

    ROUND(AVG(WIND_SPEED), 2) AS AVG_WIND_SPEED,

    COUNT(*) AS READING_COUNT

FROM REAL_TIME_PIPELINE.SILVER.WEATHER_CLEAN

WHERE WEATHER_TIMESTAMP IS NOT NULL

GROUP BY DATE_TRUNC('HOUR', WEATHER_TIMESTAMP);